services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flaskdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  flask:
    build: .
    container_name: flask-ci
    environment:
      FLASK_ENV: development
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge

