apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-app
spec:
  selector:
    app: flask-app
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30475
      protocol: TCP

