apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-container
          image: vahidevs/flask-ci-app
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_HOST
              value: db
            - name: DATABASE_NAME
              value: flaskdb
            - name: DATABASE_USER
              value: flaskuser
            - name: DATABASE_PASSWORD
              value: flaskpass

