apiVersion: v1
kind: Config
clusters:
- name: minikube
  cluster:
    certificate-authority-data: <ca.b64 məzmunu buraya>
    server: https://192.168.49.2:8443

contexts:
- name: minikube
  context:
    cluster: minikube
    user: minikube
    namespace: default

current-context: minikube

users:
- name: minikube
  user:
    client-certificate-data: <client.crt.b64 məzmunu buraya>
    client-key-data: <client.key.b64 məzmunu buraya>

